[window]
decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "JetBrainsMonoNLNerdFont"
bold.family = "JetBrainsMonoNLNerdFont"
italic.family = "JetBrainsMonoNLNerdFont"
bold_italic.family = "JetBrainsMonoNLNerdFont"
size = 12

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black = '#282828'
red = '#cc241d'
green = '#98971a'
yellow = '#d79921'
blue = '#458588'
magenta = '#b16286'
cyan = '#689d6a'
white = '#a89984'

# Bright colors
[colors.bright]
black = '#928374'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#8ec07c'
white = '#ebdbb2'

# [colors.primary]
# background = "#2e3440"
# foreground = "#d8dee9"
# dim_foreground = "#a5abb6"
#
# [colors.cursor]
# text = "#2e3440"
# cursor = "#d8dee9"
#
# [colors.vi_mode_cursor]
# text = "#2e3440"
# cursor = "#d8dee9"
#
# [colors.selection]
# text = "CellForeground"
# background = "#4c566a"
#
# [colors.search.matches]
# foreground = "CellBackground"
# background = "#88c0d0"
#
# [colors.footer_bar]
# background = "#434c5e"
# foreground = "#d8dee9"

# [colors.normal]
# black = "#3b4252"
# red = "#bf616a"
# green = "#a3be8c"
# yellow = "#ebcb8b"
# blue = "#81a1c1"
# magenta = "#b48ead"
# cyan = "#88c0d0"
# white = "#e5e9f0"
#
# [colors.bright]
# black = "#4c566a"
# red = "#bf616a"
# green = "#a3be8c"
# yellow = "#ebcb8b"
# blue = "#81a1c1"
# magenta = "#b48ead"
# cyan = "#8fbcbb"
# white = "#eceff4"
#
# [colors.dim]
# black = "#373e4d"
# red = "#94545d"
# green = "#809575"
# yellow = "#b29e75"
# blue = "#68809a"
# magenta = "#8c738c"
# cyan = "#6d96a5"
# white = "#aeb3bb"

[env]
term = "xterm-256color"
