require('options')
require('keymaps')
require('plugins.lazy')
require('plugins.keymaps')
require('plugins.options')
require('plugins.lsp.mason')
require('plugins.lsp.lspsaga')
require('plugins.lsp.lspconfig')
